# github pages we cannot customize
lsi: false
safe: true
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
incremental: false
highlighter: rouge
gist:
  noscript: false
# customize
markdown: kramdown
quiet: false
kramdown:
  input: GFM
  hard_wrap: false
  template: '' # cannot customize
  math_engine: mathjax # cannot customize
  syntax_highligher: rouge # cannot customize
jailed: false
plugins:
  - jekyll-gist
  - jekyll-paginate

# This is the default format.
# # For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title
permalink: /:year/:month/:day/:title/

# https://jekyllrb.com/docs/collections/
# Not everything is a post or a page.
# Collections allow you to define a new type of document that behave like Pages or Posts do normally,
# but also have their own unique properties and namespace.
collections:
  fragments:
    output: true

title: Benjamin Fleischer
tagline: My space
author:
  name: Benjamin Fleischer
  email: hello@benjaminfleischer.com
  github: bf4
  twitter: hazula
  # feedburner: feedname
  gravatar_url: https://gravatar.com/userimage/455248/07b6758e7d309cff827fd0b287281639.png
  linkedin: http://www.linkedin.com/in/benjaminfleischer

# Additional configuration is in the _data folder

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
url: &url http://benjaminfleischer.com
production_url: *url

exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
  - "Rakefile"
  - "_backup"
  - "_ember"
  - "_legacy"
  - "_rake"
  - "_snippets"
  - "_thoughts"
