markdown: rdiscount
pygments: true
lsi: false
safe: true
permalink: /:year/:month/:day/:title
auto: true
rdiscount:
  extensions: [smart autolink]

name: Benjamin Fleischer
url: http://benjaminfleischer.com
description: My space
twitter: hazula
github: bf4
gravatar_url: http://en.gravatar.com/userimage/455248/5fa647438e683b85d7fdf03ed74220da.jpeg
linkedin: http://www.linkedin.com/in/benjaminfleischer
resume_link: /resume.html
resume_link_text: resume
